-- ONE TEN Supabase/Postgres SQL
-- Paste this in Supabase SQL Editor.
-- Admin login remains: onetenadmin / oneten.
-- API keys and login sessions are intentionally not included.

begin;

create table if not exists admin_users (
  id bigint generated by default as identity primary key,
  username text unique not null,
  password_hash text not null,
  created_at text not null
);

create table if not exists customers (
  id bigint generated by default as identity primary key,
  name text not null,
  email text unique not null,
  password_hash text not null,
  created_at text not null
);

create table if not exists sessions (
  token text primary key,
  user_type text not null,
  user_id bigint not null,
  created_at text not null
);

create table if not exists categories (
  id bigint generated by default as identity primary key,
  name text unique not null,
  description text default '',
  price_mode text default 'range',
  sort_order integer default 0,
  created_at text not null
);

create table if not exists products (
  id bigint generated by default as identity primary key,
  category_id bigint references categories(id) on delete set null,
  name text not null,
  price numeric(10,2) not null,
  old_price numeric(10,2),
  badge text default '',
  rating text default '4.8',
  stock integer default 0,
  product_sizes jsonb default '[]'::jsonb,
  image text not null,
  images jsonb default '[]'::jsonb,
  crop text default 'center',
  description text default '',
  ai_type text default 'top',
  ai_images jsonb default '[]'::jsonb,
  ai_prompts jsonb default '[]'::jsonb,
  active boolean default true,
  created_at text not null
);

create table if not exists ads (
  id bigint generated by default as identity primary key,
  title text not null,
  subtitle text default '',
  button_text text default 'Shop Now',
  link text default '#/shop',
  image text not null,
  active boolean default true,
  sort_order integer default 0,
  created_at text not null
);

create table if not exists orders (
  id bigint generated by default as identity primary key,
  customer_id bigint not null references customers(id) on delete cascade,
  customer_name text not null,
  phone text not null,
  address text default '',
  status text default 'Processing',
  total numeric(10,2) not null,
  created_at text not null
);

create table if not exists order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references orders(id) on delete cascade,
  product_id bigint not null references products(id) on delete cascade,
  product_name text not null,
  product_image text default '',
  price numeric(10,2) not null,
  requested_qty integer default 1,
  qty integer not null,
  size text default '',
  status text default 'Processing'
);

create table if not exists settings (
  key text primary key,
  value text not null
);

create table if not exists newsletter_subscribers (
  id bigint generated by default as identity primary key,
  phone text unique not null,
  created_at text not null
);

alter table products add column if not exists product_sizes jsonb default '[]'::jsonb;
alter table order_items add column if not exists size text default '';

create index if not exists idx_products_category on products(category_id);
create index if not exists idx_products_active_stock on products(active, stock);
create index if not exists idx_orders_customer on orders(customer_id);
create index if not exists idx_order_items_order on order_items(order_id);

insert into admin_users (username, password_hash, created_at)
values ('onetenadmin', '35b744a8fe1df824c128bffc20a7097ce25b65ae34da5442e1268f70b697b79a', now()::text)
on conflict (username) do nothing;

insert into settings (key, value) values
  ('brand_name', 'ONE TEN'),
  ('phone', '+252 63 000 1010'),
  ('hotline', '(+252) 63 000 1010'),
  ('whatsapp_number', '0633454984'),
  ('email', 'support@oneten.shop'),
  ('location', 'Hargaysa'),
  ('footer_text', 'Men''s fashion, clean prices, Hargaysa delivery.'),
  ('about_title', 'ONE TEN Men''s Fashion'),
  ('about_body', 'ONE TEN focuses on simple, clean menswear for daily outfits. Every product stays between $1 and $10, with fast local delivery and a bold red, white, and black identity.')
on conflict (key) do update set value = excluded.value;

insert into categories (name, description, price_mode, sort_order, created_at) values
  ('Shirts', 'ONE TEN shirts from $1 to $10.', 'max10', 1, now()::text),
  ('Pants', 'ONE TEN pants from $1 to $10.', 'range', 2, now()::text),
  ('Jackets', 'ONE TEN jackets from $1 to $10.', 'max10', 3, now()::text),
  ('Accessories', 'ONE TEN accessories from $1 to $10.', 'range', 4, now()::text)
on conflict (name) do nothing;

commit;
